# Generated by Django 3.2.5 on 2021-07-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuqrcodes', '0001_initial'),
        ('foodmenu', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('qrtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuqrcodes.menuqrcodes')),
            ],
        ),
    ]
