# Generated by Django 3.2.5 on 2021-07-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qrtable',
        ),
    ]
