# Generated by Django 3.2.5 on 2021-08-20 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0005_remove_customer_qrtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 20, 13, 43, 12, 135515))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodmenu.product')),
            ],
        ),
    ]
